import {test} from 'node:test';
import assert from 'node:assert/strict';
import {calculate,initialInput,rankFor,activityPoints,relationshipPoints,frequencyPoints,completeMonths,monthsBefore,purchaseKey,MODEL} from '../lib/credit-policy.ts';
const c={day:'2026-10-01',customerId:'c',registrationComplete:true,missingRegistration:[]};
const report=rows=>({customerId:'c',fileName:'test.csv',customerLabel:'Cliente',rows});
const full={...initialInput,kind:'new',restriction:'clear',openingDate:'2020-01-01',otherSupplier:true,creditScore:1000};
const buy=(document,date,amount,purchase=purchaseKey(document))=>({document,purchase,date,amount});
test('positive maximum is 100 and rank A',()=>{const r=calculate(full,c);assert.equal(r.totalScore,100);assert.equal(r.rank,'A');assert.equal(r.rankLabel,'Estruturado')});
test('restriction is -75, not merely losing 25 points',()=>{const r=calculate({...full,restriction:'restricted'},c);assert.equal(r.totalScore,0);assert.equal(r.rank,'D')});
test('negative score is retained and mapped to D',()=>{const r=calculate({...full,restriction:'restricted',openingDate:'2026-09-01',otherSupplier:false,creditScore:0},{...c,registrationComplete:false});assert.equal(r.totalScore,-75);assert.equal(r.rank,'D')});
test('rank thresholds have no overlap',()=>{for(const [n,rank] of [[-75,'D'],[0,'D'],[34,'D'],[35,'C'],[49,'C'],[50,'B'],[69,'B'],[70,'A'],[100,'A']])assert.equal(rankFor(n),rank)});
test('activity thresholds',()=>{for(const [n,p] of [[0,0],[5,0],[6,3],[11,3],[12,6],[23,6],[24,9],[35,9],[36,12],[59,12],[60,15]])assert.equal(activityPoints(n),p)});
test('completed calendar months, not approximate days',()=>{assert.equal(completeMonths('2026-04-02','2026-10-01'),5);assert.equal(completeMonths('2026-04-01','2026-10-01'),6);assert.equal(monthsBefore('2026-08-31',6),'2026-02-28')});
test('credit score rounded to integer points',()=>{for(const [score,points] of [[0,0],[800,24],[850,26],[999,30],[1000,30]])assert.equal(calculate({...full,creditScore:score},c).criteria.find(p=>p.key==='credit').points,points)});
test('credit out of bounds and future activity date rejected',()=>{for(const score of [-1,1001,Infinity])assert.throws(()=>calculate({...full,creditScore:score},c));assert.throws(()=>calculate({...full,openingDate:'2027-01-01'},c))});
test('incomplete registration gets zero',()=>assert.equal(calculate(full,{...c,registrationComplete:false}).totalScore,80));
test('missing score is not interpreted as zero',()=>{const r=calculate({...full,creditScore:null},c);assert.equal(r.totalScore,null);assert.equal(r.rank,null)});
test('latest 25 titles only, with 0–2 days considered punctual',()=>{const rows=Array.from({length:30},(_,i)=>({document:String(i),date:`2026-09-${String(i+1).padStart(2,'0')}`,delay:i<5?30:i>=28?3:2}));const r=calculate({...full,kind:'history',paid:report(rows)},c);assert.equal(r.punctuality.analyzed,25);assert.equal(r.punctuality.onTime,23);assert.equal(r.punctuality.late,2);assert.equal(r.punctuality.percent,92);assert.equal(r.punctuality.points,23)});
test('fewer than 25 uses available records and rounds',()=>{const r=calculate({...full,kind:'history',paid:report([{document:'1',date:'2026-09-01',delay:0},{document:'2',date:'2026-09-02',delay:1},{document:'3',date:'2026-09-03',delay:3}])},c);assert.equal(r.punctuality.points,17);assert.equal(r.punctuality.analyzed,3)});
test('no titles avoids divide by zero',()=>assert.equal(calculate({...full,kind:'history',paid:report([])},c).punctuality.points,null));
test('installment grouping keeps middle component',()=>{assert.equal(purchaseKey('21938-2-1'),'21938-2');assert.equal(purchaseKey('21938-2-2'),'21938-2');assert.equal(purchaseKey('21938-3-1'),'21938-3');assert.equal(purchaseKey('INV-42'),'INV-42')});
test('sums installments before averaging unique purchases',()=>{const r=calculate({...initialInput,purchases:report([buy('21938-2-1','2026-09-01',10000),buy('21938-2-2','2026-09-01',20000),buy('other','2026-09-02',10000)]),maxOpenPurchases:3},c);assert.equal(r.limit.count,2);assert.equal(r.limit.total,40000);assert.equal(r.limit.average,20000);assert.equal(r.limit.value,60000);assert.equal(r.rank,null)});
test('exact supplied currency example',()=>{const r=calculate({...full,purchases:report([buy('x','2026-09-01',2794057)]),maxOpenPurchases:3},c);assert.equal(r.limit.value,8382171)});
test('rank, restrictions and scoring never change limit',()=>{const purchases=report([buy('x','2026-09-01',2794057)]);for(const input of [full,{...full,restriction:'restricted'},{...full,creditScore:0},{...initialInput,kind:'history'}])assert.equal(calculate({...input,purchases,maxOpenPurchases:3},c).limit.value,8382171)});
test('no old cap, segment factor, 15% buffer or R$500 rounding',()=>{const r=calculate({...full,purchases:report([buy('x','2026-09-01',10000001)]),maxOpenPurchases:3},c);assert.equal(r.limit.value,30000003)});
test('six-month range is inclusive; older purchase excluded',()=>{const r=calculate({...full,purchases:report([buy('a','2026-03-31',100),buy('b','2026-04-01',200),buy('c','2026-10-01',300)])},c);assert.equal(r.limit.count,2);assert.equal(r.limit.total,500);assert.equal(r.frequency.count,2)});
test('same purchase dates spanning cutoff are grouped first',()=>{const r=calculate({...full,purchases:report([buy('1-1-1','2026-03-01',100),buy('1-1-2','2026-05-01',100)])},c);assert.equal(r.limit.count,0)});
test('duplicate installment not counted twice, conflict rejected',()=>{const row=buy('1-1-1','2026-09-01',100);assert.equal(calculate({...full,purchases:report([row,row])},c).limit.total,100);assert.throws(()=>calculate({...full,purchases:report([row,{...row,amount:200}])},c))});
test('frequency thresholds',()=>{for(const [n,p] of [[0,0],[2,0],[3,3],[5,3],[6,6],[8,6],[9,8],[11,8],[12,10],[50,10]])assert.equal(frequencyPoints(n),p)});
test('relationship thresholds',()=>{for(const [n,p] of [[0,0],[2,0],[3,2],[5,2],[6,4],[11,4],[12,6],[17,6],[18,8],[23,8],[24,10]])assert.equal(relationshipPoints(n),p)});
test('earliest record used unless first purchase explicitly entered',()=>{const purchases=report([buy('x','2024-01-01',100)]);assert.equal(calculate({...full,kind:'history',purchases},c).firstPurchase,'2024-01-01');assert.equal(calculate({...full,kind:'history',purchases,firstPurchaseDate:'2023-01-01'},c).firstPurchase,'2023-01-01')});
test('history maximum 100',()=>{const rows=Array.from({length:12},(_,i)=>buy('x'+i,'2026-09-01',100));const r=calculate({...full,kind:'history',firstPurchaseDate:'2024-01-01',purchases:report(rows),paid:report([{document:'1',date:'2026-09-01',delay:2}])},c);assert.equal(r.totalScore,100)});
test('report belonging to another customer is rejected',()=>assert.throws(()=>calculate({...full,purchases:{...report([]),customerId:'other'}},c)));
test('zero multiplier is explicit zero, missing is unknown',()=>{const purchases=report([buy('x','2026-09-01',100)]);assert.equal(calculate({...full,purchases,maxOpenPurchases:0},c).limit.value,0);assert.equal(calculate({...full,purchases},c).limit.value,null)});
test('fractional max purchases and negative money rejected',()=>{assert.throws(()=>calculate({...full,maxOpenPurchases:1.5},c));assert.throws(()=>calculate({...full,purchases:report([buy('x','2026-09-01',-1)])},c))});

test('limit rounds only the final result, not the intermediate mean',()=>{const r=calculate({...full,purchases:report([buy('a','2026-09-01',33),buy('b','2026-09-01',33),buy('c','2026-09-01',34)]),maxOpenPurchases:3},c);assert.equal(r.limit.average,33);assert.equal(r.limit.value,100)});

test('latest N selects grouped purchases by date and preserves six-month rank frequency',()=>{
 const purchases=report([buy('old','2026-03-01',999999),buy('a','2026-04-01',10000),buy('b','2026-08-01',20000),buy('9-2-2','2026-09-01',30000),buy('9-2-1','2026-09-01',40000)]);
 const input={...full,kind:'history',purchases,maxOpenPurchases:3};
 const all=calculate(input,c),one=calculate({...input,latestPurchaseCount:1},c);
 assert.equal(one.limit.count,1);assert.equal(one.limit.availableCount,3);assert.equal(one.limit.total,70000);assert.equal(one.limit.average,70000);assert.equal(one.limit.value,210000);assert.equal(one.limit.purchases[0].installments,2);
 assert.deepEqual(one.frequency,all.frequency);assert.deepEqual(one.criteria,all.criteria);
 const two=calculate({...input,latestPurchaseCount:2},c);assert.equal(two.limit.total,90000);assert.equal(two.limit.value,135000);
 assert.equal(calculate({...input,latestPurchaseCount:100},c).limit.count,3);
 const legacy={...input};delete legacy.latestPurchaseCount;assert.deepEqual(calculate(legacy,c),all);
 assert.equal(calculate({...input,latestPurchaseCount:1,purchases:report([])},c).limit.value,null);
 for(const n of [0,-1,1.5,Infinity,'2'])assert.throws(()=>calculate({...input,latestPurchaseCount:n},c));
});
