import {test} from 'node:test';import assert from 'node:assert/strict';import ts from 'typescript';import {readFileSync} from 'node:fs';
test('export authenticates and uses DB limit, ignoring posted financial values',async()=>{
 const state={authorized:true,origin:true,audits:[],customer:{id:'c',customer_code:'42',tax_id:'12345678901',name:'Teste',credit_limit:456789}};globalThis.__neveraTest=state;
 let src=readFileSync(new URL('../app/api/nevera-export/route.ts',import.meta.url),'utf8').replace("import {requireUser,audit} from '@/lib/auth';",`const requireUser=async()=>{if(!globalThis.__neveraTest.authorized)throw Error('Sem acesso');return {name:'Operador',login:'operador'}};const audit=async(...a)=>globalThis.__neveraTest.audits.push(a);`).replace("import {db,failure,sameOrigin} from '@/lib/server';",`const db=()=>({prepare:()=>({bind:()=>({first:async()=>globalThis.__neveraTest.customer})})});const failure=e=>Response.json({error:e.message},{status:400});const sameOrigin=()=>{if(!globalThis.__neveraTest.origin)throw Error('Origem inválida')};`).replace("'@/lib/nevera-export'",JSON.stringify(new URL('../lib/nevera-export.ts',import.meta.url).href));
 const js=ts.transpileModule(src,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;const {POST}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));const send=()=>POST(new Request('https://test/api/nevera-export',{method:'POST',body:JSON.stringify({id:'c',limitCents:999999,actor:'Falso'})}));
 let response=await send();assert.equal(response.status,200);let payload=await response.json();assert.equal(payload.limitCents,456789);assert.equal(payload.actor,'Operador (operador)');assert.match(state.audits[0][4],/Não confirma gravação/);
 state.customer.credit_limit=123;payload=await (await send()).json();assert.equal(payload.limitCents,123);
 state.authorized=false;assert.equal((await send()).status,400);state.authorized=true;state.origin=false;assert.equal((await send()).status,400);delete globalThis.__neveraTest;
});
