import {test} from 'node:test';
import assert from 'node:assert/strict';
import {calculate,initialInput,newWeights} from '../lib/credit-policy.ts';
const c={complete:false,currentLimit:9000,currentTerm:14,exposure:1000,overdue:0,curve:'B',reactivated:false,groupOverdue:false,day:'2026-10-01'};
test('all fields optional: blank input is saveable and never becomes E or zero credit',()=>{const r=calculate(initialInput,c);assert.equal(r.ready,true);assert.equal(r.partial,true);assert.equal(r.rank,null);assert.equal(r.score,null);assert.equal(r.limit,null);assert.equal(r.term,null);assert.equal(r.available,null)});
test('compute need using provided purchases without requiring the removed controls',()=>{const r=calculate({...initialInput,weekly:1000,order:500},c);assert.equal(r.ready,true);assert.equal(r.caps.necessidade,1725);assert.equal(r.caps.cliente_5,null);assert.equal(r.limit,null)});
test('incomplete points show partial sum without inventing a class',()=>{const r=calculate({...initialInput,points:{score:25}},c);assert.equal(r.score,25);assert.equal(r.rank,null);assert.equal(r.scoreComplete,false)});
test('estimate from known caps, never silently treating missing portfolio as zero',()=>{const r=calculate({...initialInput,weekly:10000,order:5000,points:Object.fromEntries(newWeights.map(([k,,v])=>[k,v]))},c);assert.equal(r.ready,true);assert.equal(r.rank,'A');assert.equal(r.limit,8000);assert.equal(r.caps.cliente_5,null);assert.equal(r.partial,true)});
test('explicit zero is distinct from missing data',()=>{const r=calculate({...initialInput,weekly:1000,order:500,portfolio:0,points:Object.fromEntries(newWeights.map(([k,,v])=>[k,v]))},c);assert.equal(r.limit,0)});
test('optional does not accept an invalid provided number',()=>{const r=calculate({...initialInput,weekly:-1},c);assert.equal(r.ready,false);assert.ok(r.pending.length)});
test('partial analysis preserves blocking information without requiring extra fields',()=>{const r=calculate({...initialInput,permanentBlock:true},c);assert.equal(r.ready,true);assert.equal(r.blocked,true);assert.equal(r.limit,null);assert.equal(r.term,null)});
