'use client';
import {useEffect,useState} from 'react';
import {calculate,initialInput,newWeights,existingWeights,segments,numericLabels,type Input,type Context} from '@/lib/credit-policy';
import {money} from '@/lib/board';
import {readApiResponse} from '@/lib/api-response';

type Data={revision:string;erp:{note:string;occurred_at:string}|null;customer:{name:string;category:string|null};context:Context;records:{id:string;status:string;approved_at:string|null;payload:{input:Input;report:string;result:ReturnType<typeof calculate>}|null}[]};
export function CreditAssessment({customerId,onChanged}:{customerId:string;onChanged:()=>Promise<unknown>}){
 const [data,setData]=useState<Data|null>(null),[input,setInput]=useState<Input>(initialInput),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[approver,setApprover]=useState(''),[evidence,setEvidence]=useState('');
 async function load(){const response=await fetch('/api/credit-assessment?id='+encodeURIComponent(customerId),{cache:'no-store'});const next=await readApiResponse<Data>(response);setData(next);setInput(next.records.find(r=>r.payload)?.payload?.input??initialInput);}
 useEffect(()=>{let active=true;setData(null);setError('');fetch('/api/credit-assessment?id='+encodeURIComponent(customerId),{cache:'no-store'}).then(r=>readApiResponse<Data>(r)).then(next=>{if(active){setData(next);setInput(next.records.find(r=>r.payload)?.payload?.input??initialInput);}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false;};},[customerId]);
 const set=<K extends keyof Input>(key:K,value:Input[K])=>{setInput(old=>({...old,[key]:value}));setNotice('');};
 async function save(action:string){setBusy(true);setError('');try{const response=await fetch('/api/credit-assessment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:customerId,revision:data?.revision,input,action,approver,evidence,authority:result?.authority})});await readApiResponse(response);await load();await onChanged();setNotice(action==='erp'?'Confirmação de atualização no ERP registrada.':action==='approve'?'Decisão registrada. Classe, limite e prazo preenchidos no cadastro.':action==='submit'?'Recomendação salva e enviada para aprovação.':'Rascunho salvo.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const result=data?calculate(input,data.context):null;
 const number=(key:keyof Input,help:string)=> <label key={key}>{numericLabels[key]??key}<input type="number" min="0" step={['months2','months4','lateEvents'].includes(key)?'1':'0.01'} value={input[key]===null?'':String(input[key])} disabled={busy} onChange={e=>set(key,(e.target.value===''?null:Number(e.target.value)) as never)}/><small>{help}</small></label>;
 const check=(key:keyof Input,label:string)=> <label className="policy-check" key={key}><input type="checkbox" checked={!!input[key]} disabled={busy} onChange={e=>set(key,e.target.checked as never)}/>{label}</label>;
 const text=(key:keyof Input,label:string,help:string)=> <label>{label}<textarea rows={3} value={String(input[key])} maxLength={4000} disabled={busy} onChange={e=>set(key,e.target.value as never)}/><small>{help}</small></label>;
 if(!data||!result)return <div role="status">{error||'Carregando dados para análise…'}</div>;
 const current=data.records.find(r=>['in_progress','awaiting_approval'].includes(r.status));
 const dirty=JSON.stringify(input)!==JSON.stringify(current?.payload?.input);
 return <section className="policy-assessment"><header><h3>Análise de crédito guiada</h3><p>Política King Foods v6.0 • 23/09/2026. Preencha as evidências; os resultados são calculados automaticamente e o cadastro é atualizado após o registro da aprovação.</p></header>
 <details open><summary>1. Cadastro e conferências obrigatórias</summary><div className="policy-fields"><p className={data.context.complete?'':'error'}>{data.context.complete?'Dados básicos do cadastro completos.':'Cadastro incompleto: confira foto, titular, documento, pagador, contatos e endereço confirmado na aba Dados do cadastro.'}</p><label>Tipo de análise<select value={input.kind} onChange={e=>set('kind',e.target.value as Input['kind'])}><option value="new">Cliente novo ou reativado</option><option value="existing">Cliente com histórico King Foods</option></select><small>Mais de 180 dias sem comprar exige análise completa como novo.</small></label><label>Segmento confirmado<select value={input.segment} onChange={e=>set('segment',e.target.value as Input['segment'])}>{Object.entries(segments).map(([key,s])=><option key={key} value={key}>{s.label}</option>)}</select><small>Categoria cadastrada: {data.customer.category||'não informada'}. Estruturado: supermercados, cozinhas industriais, indústrias e hotéis. Food service: bares e restaurantes. Revenda: açougues, empórios, mercearias e distribuidoras.</small></label>{check('categoryConfirmed','Confirmei que a categoria corresponde ao segmento (8).')}{check('contactValidated','O pagador confirmou que este é o contato correto (5.1).')}{text('contactEvidence','Registro da validação do pagador','Informe data, hora, canal e resposta recebida. Marcar a caixa sozinho não valida o contato.')}{check('groupOverdue','Há título vencido em outro integrante do grupo: bloqueia todos os cadastros.')}{check('groupChecked','Conferi vínculos de titular, sócios, endereço e nome fantasia (8.1).')}{check('portfolioChecked','Conferi a carteira completa, incluindo risco retido em duplicatas descontadas (9.6).')}{check('documentsDoubt','A análise levantou dúvida: exigir documentação adicional em qualquer valor.')}{check('additionalDocuments','Documentos adicionais conferidos: fornecedor, identidade e atividade (5.4).')}{check('directorReferred','Cliente indicado pela própria Diretoria, com risco assumido por escrito (12).')}{text('checks','Consultas, documentos e histórico conferidos','Registre fonte, data e responsável; situação cadastral, restrições, protestos, atividade, compras em 6 meses e documentos. Consulta processual acima de R$ 15.000. Documentos adicionais também são exigidos quando houver dúvida (5.4 e 6).')}</div></details>
 <details open><summary>2. Notas externas e pontuação interna</summary><div className="policy-fields">{(['spc','serasa'] as const).map(key=><div className="policy-fields" key={key}><label>Nota {key.toUpperCase()} (0–1.000)<input type="number" min="0" max="1000" value={input[key]??''} onChange={e=>set(key,e.target.value===''?null:Number(e.target.value))}/></label><label>Data da consulta<input type="date" max={data.context.day} value={input[key==='spc'?'spcDate':'serasaDate']} onChange={e=>set(key==='spc'?'spcDate':'serasaDate',e.target.value)}/></label></div>)}<p>Serasa é a referência; SPC substitui somente quando Serasa não tem nota válida. Validade: 90 dias. As duas notas não são somadas.</p><p><strong>Pontos avaliados pelo analista:</strong> o PDF define os pesos abaixo, mas não define faixas de conversão dos indicadores. Para manter fidelidade à política, nenhuma fórmula de pontuação foi inventada.</p>{(input.kind==='new'||data.context.reactivated?newWeights:existingWeights).map(([key,label,max])=><label key={key}>{label} • até {max} pontos<input type="number" min="0" max={max} step="0.01" value={input.points[key]??''} onChange={e=>set('points',{...input.points,[key]:e.target.value===''?null:Number(e.target.value)})}/></label>)}{text('justification','Fundamentos da pontuação','Explique os pontos atribuídos a cada item com base nas evidências. A soma e a classe são automáticas (7.2–7.3).')}</div></details>
 <details open><summary>3. Compras, necessidade e tetos do limite</summary><div className="policy-fields">{number('requested','Valor que o cliente está solicitando; não é um limite garantido.')}{number('weekly','Média semanal comprovada; para novo, estimativa fundamentada no parecer.')}{number('order','Valor médio de um pedido, usado na necessidade e em reduções previstas.')}{number('pendingOrder','Pedido atual ainda não incluído na exposição em aberto; informe 0 se não houver.')}{number('portfolio','Posição completa na data da análise. Não use apenas os títulos visíveis na tela.')}{number('dailyRevenue','Base diária conferida: teto global = 20 dias de faturamento.')}{number('otherGroup','Saldo aberto dos demais cadastros vinculados. Informe 0 se não houver grupo.')}{input.kind==='existing'&&!data.context.reactivated&&<>{number('received','Somente principal conciliado: sem juros, cancelamentos ou duplicidades.')}{number('peak','Maior exposição comprovadamente quitada de forma correta.')}{number('months2','Quantidade entre 0 e 6. Prazo de 14 dias exige pelo menos 4 meses.')}{number('months4','Quantidade entre 0 e 6. Prazo de 21 dias exige 5 meses; 28 dias exige 6.')}{number('onTime','Percentual dos títulos pagos pontualmente nos últimos 6 meses.')}{number('lateEvents','Ocorrências acima de 5 dias nos últimos 6 meses.')}{number('maxDelay','Maior atraso do evento sendo analisado. Informe 0 se não houve atraso.')}{number('shortEvents','Contador separado dos atrasos acima de 5 dias.')}</>}{check('growing','Compras em crescimento comprovado: folga de 25% (caso contrário, 15%).')}<label>Prazo solicitado<select value={input.requestedTerm} onChange={e=>set('requestedTerm',Number(e.target.value))}>{[0,7,14,21,28].map(v=><option key={v} value={v}>{v===0?'À vista':`${v} dias`}</option>)}</select><small>Entrada em 7 dias; sobe no máximo um degrau por revisão. Revenda: máximo de 14 dias.</small></label></div></details>
 <details open><summary>4. Restrições e condições que impedem crédito</summary><div className="policy-fields"><label>Situação externa<select value={input.restriction} onChange={e=>set('restriction',e.target.value as Input['restriction'])}><option value="none">Sem restrições ativas</option><option value="small">Até R$ 5.000, sem protesto e fora de fornecedor de alimentos</option><option value="relevant">Acima de R$ 5.000 ou fornecedor de alimentos</option><option value="protest">Protesto ativo</option><option value="judicial">Recuperação judicial ou falência</option></select></label>{check('goodHistory','Bom histórico interno comprovado para a restrição de até R$ 5.000.') }<label>Acordo<select value={input.agreement} onChange={e=>set('agreement',e.target.value as Input['agreement'])}><option value="none">Sem acordo em andamento</option><option value="performing">Assinado, reconhecido e adimplente: somente à vista</option><option value="blocked">Não formalizado ou descumprido: venda suspensa</option></select></label><label>Data do evento de atraso<input type="date" max={data.context.day} value={input.incidentDate} onChange={e=>set('incidentDate',e.target.value)}/></label><label>Data da baixa do pagamento<input type="date" max={data.context.day} value={input.settlementDate} onChange={e=>set('settlementDate',e.target.value)}/></label><label>Prazo anterior à penalidade<select value={input.prePenaltyTerm} onChange={e=>set('prePenaltyTerm',Number(e.target.value))}>{[0,7,14,21,28].map(v=><option key={v} value={v}>{v} dias</option>)}</select><small>Evita reduzir duas vezes pelo mesmo evento.</small></label>{check('permanentBlock','Há bloqueio permanente registrado.') }<label>Somente à vista até<input type="date" value={input.cashUntil} onChange={e=>set('cashUntil',e.target.value)}/><small>Informe a maior data aplicável entre reincidência e retorno após pagamento (16.3–16.4).</small></label><label>Limite congelado até<input type="date" value={input.freezeUntil} onChange={e=>set('freezeUntil',e.target.value)}/></label>{check('conditionsChecked','Conferi validade cadastral, consultas obrigatórias, protestos, acordos e todas as penalidades ainda vigentes.')}{text('risks','Riscos, mitigadores e condições','Registre também pendências do grupo, atrasos quitados, protesto, acordos, validade cadastral e penalidades. Não conclua com impedimentos sem tratamento.')}</div></details>
 <section className="policy-result" aria-live="polite"><h3>5. Resultado {result.ready?'calculado':'provisório • há pendências'}</h3><div className="customer-detail-metrics"><article><span>Pontuação / classe</span><strong>{result.score} / 100 • {result.rank}</strong><small>A classe será gravada após aprovação.</small></article><article><span>Limite recomendado</span><strong>{money(result.limit*100)}</strong><small>Menor teto, arredondado para baixo em R$ 500.</small></article><article><span>Prazo recomendado</span><strong>{result.term?`${result.term} dias`:'À vista'}</strong><small>{result.blocked?'Venda bloqueada: à vista também não está liberada.':'Sujeito à aprovação.'}</small></article><article><span>Alçada exigida</span><strong>{result.authority}</strong><small>Quem deve decidir sobre o parecer.</small></article></div><dl className="policy-caps">{Object.entries(result.caps).map(([key,value])=><div key={key}><dt>{{necessidade:'Necessidade com folga (9.2)',classe_segmento:'Teto da classe × segmento',primeiro_limite:'Teto inicial (cliente novo)',historico:'Teto do histórico conciliado',grupo_classe:'Espaço do grupo no teto da classe',cliente_5:'5% da carteira por cliente',grupo_8:'8% da carteira menos outros integrantes',carteira_20:'Espaço em 20 dias de faturamento'}[key]??key}</dt><dd>{money(value*100)}</dd></div>)}</dl><p>Utilizado, incluindo pedido: {money(result.used*100)} • Disponível proposto: {money(result.available*100)}.</p><p>Validade proposta do limite: {result.validity??'sem crédito'} • Próxima revisão: {result.nextReview}.</p>{result.warnings.map(v=><p key={v}>{v}</p>)}{!!result.pending.length&&<div role="status"><h4>O que falta para concluir</h4><ul>{result.pending.map(v=><li key={v}>{v}</li>)}</ul></div>}</section>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="policy-actions"><button type="button" className="secondary-button" disabled={busy} onClick={()=>void save('draft')}>Salvar rascunho</button><button type="button" className="primary" disabled={busy||!result.ready} onClick={()=>void save('submit')}>Gerar parecer e enviar para aprovação</button></div>
 {current?.status==='awaiting_approval'&&<section className="policy-approval"><h3>Registrar decisão da alçada</h3><p>Alçada exigida: <strong>{result.authority}</strong>. O acesso de administrador ao sistema não substitui a decisão dessa alçada.</p><label>Nome de quem aprovou<input value={approver} maxLength={120} onChange={e=>setApprover(e.target.value)}/></label><label>Referência da aprovação formal<textarea value={evidence} maxLength={2000} onChange={e=>setEvidence(e.target.value)} placeholder="Data, decisão, condições e referência do documento ou registro"/></label><button type="button" className="primary" disabled={busy||dirty||!result.ready||!approver.trim()||!evidence.trim()} onClick={()=>void save('approve')}>Registrar aprovação e preencher cadastro</button>{dirty&&<p>Envie novamente a recomendação após alterar os dados.</p>}</section>}
 {data.records.some(r=>r.status==='approved')&&<details><summary>Atualização do ERP (capítulos 11 e 18)</summary><p>Copie o parecer aprovado para o ERP no mesmo dia da decisão. Depois registre a confirmação abaixo.</p>{data.erp&&<p>Última confirmação: {data.erp.occurred_at} • {data.erp.note}</p>}<label>Referência da atualização<input value={evidence} maxLength={2000} onChange={e=>setEvidence(e.target.value)}/></label><button type="button" className="secondary-button" disabled={busy||!evidence.trim()} onClick={()=>void save('erp')}>Confirmar que atualizei o ERP</button></details>}
 <details><summary>Pareceres e decisões anteriores ({data.records.length})</summary>{data.records.map(r=><article key={r.id}><strong>{r.status==='approved'?'Aprovado':r.status==='awaiting_approval'?'Aguardando aprovação':'Rascunho'}</strong><pre className="policy-report">{r.payload?.report??'Análise anterior: consulte o histórico no módulo Análises.'}</pre></article>)}</details>
 </section>;
}
