import { db } from '@/lib/server';

export type AuthUser={id:string;name:string;login:string;role:string};
const cookieName='kf_session';
const enc=new TextEncoder();
function hex(bytes:Uint8Array){return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');}
async function digest(value:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value))));}
export async function hashPassword(password:string){const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bytes=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:100000,hash:'SHA-256'},key,256);return `pbkdf2-sha256:100000:${hex(salt)}:${hex(new Uint8Array(bytes))}`;}
export async function verifyPassword(password:string,stored:string){const [algorithm,count,salt,expected]=stored.split(':');if(algorithm!=='pbkdf2-sha256'||!/^\d+$/.test(count)||Number(count)<1||Number(count)>100000||!salt||!expected)return false;const raw=new Uint8Array((salt.match(/.{2}/g)??[]).map(s=>parseInt(s,16)));const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const value=hex(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt:raw,iterations:Number(count),hash:'SHA-256'},key,256)));if(value.length!==expected.length)return false;let difference=0;for(let i=0;i<value.length;i++)difference|=value.charCodeAt(i)^expected.charCodeAt(i);return difference===0;}
export function validatePassword(password:unknown){if(typeof password!=='string'||password.length<12||password.length>128)throw new Error('A senha deve ter de 12 a 128 caracteres.');}
export function validateIdentity(name:unknown,login:unknown){if(typeof name!=='string'||!name.trim()||name.length>120)throw new Error('Informe o nome (até 120 caracteres).');if(typeof login!=='string'||!/^[a-zA-Z0-9._-]{3,50}$/.test(login.trim()))throw new Error('O login deve ter de 3 a 50 caracteres: letras, números, ponto, hífen ou sublinhado.');return {name:name.trim(),login:login.trim().toLowerCase()};}
export function getToken(request:Request){return request.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='))?.slice(cookieName.length+1)??'';}
export async function currentUser(request:Request):Promise<AuthUser|null>{const token=getToken(request);if(!/^[a-f0-9]{64}$/.test(token))return null;const row=await db().prepare('SELECT u.id,u.name,u.login,u.role FROM user_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1').bind(await digest(token),new Date().toISOString()).first() as AuthUser|null;return row??null;}
export class Unauthenticated extends Error{constructor(){super('Sessão encerrada. Entre novamente.');this.name='Unauthenticated';}}
export async function requireUser(request:Request){const user=await currentUser(request);if(!user)throw new Unauthenticated();return user;}
export async function createSession(userId:string){const token=hex(crypto.getRandomValues(new Uint8Array(32)));const expiration=new Date(Date.now()+7*86400000);await db().prepare('INSERT INTO user_sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').bind(await digest(token),userId,expiration.toISOString(),new Date().toISOString()).run();return `${cookieName}=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`;}
export async function revokeSession(request:Request){const token=getToken(request);if(token)await db().prepare('DELETE FROM user_sessions WHERE token_hash=?').bind(await digest(token)).run();}
export function clearSession(){return `${cookieName}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`;}
export async function revokeUserSessions(id:string){await db().prepare('DELETE FROM user_sessions WHERE user_id=?').bind(id).run();}
export async function audit(user:AuthUser,action:string,entityType:string,entityId:string|null,details=''){await db().prepare('INSERT INTO audit_events(id,user_id,user_name,action,entity_type,entity_id,details,occurred_at) VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),user.id,user.name,action,entityType,entityId,details.slice(0,3000),new Date().toISOString()).run();}
