import {db,failure,sameOrigin} from '@/lib/server';
import {audit,hashPassword,requireUser,revokeUserSessions,validateIdentity,validatePassword} from '@/lib/auth';
export async function GET(request:Request){try{await requireUser(request);const rows=await db().prepare('SELECT id,name,login,role,active,created_at,updated_at FROM users ORDER BY created_at').all();return Response.json({users:rows.results});}catch(e){return failure(e);}}
export async function POST(request:Request){try{sameOrigin(request);const actor=await requireUser(request),body=await request.json() as Record<string,unknown>,d=db(),action=String(body.action??'');
 if(action==='create'){const {name,login}=validateIdentity(body.name,body.login);validatePassword(body.password);const id=crypto.randomUUID(),now=new Date().toISOString();await d.prepare("INSERT INTO users(id,name,login,password_hash,role,active,created_at,updated_at) VALUES(?,?,?,?,'admin',1,?,?)").bind(id,name,login,await hashPassword(body.password as string),now,now).run();await audit(actor,'create_user','user',id,login);return Response.json({ok:true,id});}
 const id=String(body.id??''),target=await d.prepare('SELECT id,name,login,active FROM users WHERE id=?').bind(id).first() as {id:string;name:string;login:string;active:number}|null;if(!target)return Response.json({error:'Usuário não encontrado.'},{status:404});
 if(action==='edit'){const {name,login}=validateIdentity(body.name,body.login);await d.prepare('UPDATE users SET name=?,login=?,updated_at=? WHERE id=?').bind(name,login,new Date().toISOString(),id).run();await audit(actor,'edit_user','user',id,`${target.name} (${target.login}) → ${name} (${login})`);}
 else if(action==='reset_password'){validatePassword(body.password);await d.prepare('UPDATE users SET password_hash=?,failed_logins=0,locked_until=NULL,updated_at=? WHERE id=?').bind(await hashPassword(body.password as string),new Date().toISOString(),id).run();await revokeUserSessions(id);await audit(actor,'reset_password','user',id,target.login);}
 else if(action==='set_active'){const active=body.active===true?1:0;if(!active&&id===actor.id)throw new Error('Você não pode desativar sua própria conta.');await d.prepare('UPDATE users SET active=?,updated_at=? WHERE id=?').bind(active,new Date().toISOString(),id).run();if(!active)await revokeUserSessions(id);await audit(actor,active?'activate_user':'deactivate_user','user',id,target.login);}
 else return Response.json({error:'Ação inválida.'},{status:400});return Response.json({ok:true});
}catch(e){if(e instanceof Error&&e.message.includes('UNIQUE constraint failed'))return Response.json({error:'Este login já está cadastrado.'},{status:409});return failure(e);}}
