import {requireUser, audit} from '@/lib/auth';
import {db,failure,sameOrigin} from '@/lib/server';
import {validTaxId} from '@/lib/policy';

function validRow(row:any){return row&&typeof row.customer_code==='string'&&row.customer_code.trim().length>0&&row.customer_code.trim().length<=80&&typeof row.name==='string'&&row.name.trim().length>0&&row.name.length<=200&&typeof row.tax_id==='string'&&validTaxId(row.tax_id)&&['seller_name','last_sale_date','address','city','category'].every(key=>typeof row[key]==='string'&&row[key].length<=500);}
export async function POST(request:Request){try{
    const authUser=await requireUser(request);
 sameOrigin(request);const body=await request.json() as any;if(!Array.isArray(body.rows)||body.rows.length>10000||!body.rows.every(validRow))throw new Error('A prévia contém dados inválidos. Selecione o CSV novamente.');
 const d=db(),current=await d.prepare('SELECT id,customer_code,tax_id FROM customers').all(),byCode=new Map<string,any>(),byTax=new Map<string,any>();for(const customer of current.results as any[]){if(customer.customer_code)byCode.set(String(customer.customer_code),customer);if(customer.tax_id)byTax.set(String(customer.tax_id).replace(/\D/g,''),customer);}
 const seenCodes=new Set<string>(),planned:any[]=[];for(const row of body.rows){const code=String(row.customer_code).trim(),tax=String(row.tax_id).replace(/\D/g,'');if(seenCodes.has(code))throw new Error(`O código ${code} aparece mais de uma vez na prévia.`);seenCodes.add(code);const codeCustomer=byCode.get(code),taxCustomer=byTax.get(tax);if(codeCustomer&&taxCustomer&&codeCustomer.id!==taxCustomer.id)throw new Error(`O código ${code} e o CPF/CNPJ informado pertencem a cadastros diferentes.`);if(taxCustomer&&taxCustomer.customer_code&&taxCustomer.customer_code!==code&&!String(taxCustomer.customer_code).startsWith('LEGACY-'))throw new Error(`O documento do código ${code} já está associado a outro código.`);const target=codeCustomer??taxCustomer??null;const id=target?String(target.id):crypto.randomUUID();planned.push({row:{...row,customer_code:code,tax_id:tax},target,id});const customer={id,customer_code:code,tax_id:tax};byCode.set(code,customer);byTax.set(tax,customer);}
 const now=new Date().toISOString(),ops:any[]=[];for(const item of planned){const r=item.row;if(item.target){ops.push(d.prepare('UPDATE customers SET customer_code=?,tax_id=?,name=?,seller_name=?,last_sale_date=?,address=?,city=?,category=?,updated_at=? WHERE id=?').bind(r.customer_code,r.tax_id,r.name,r.seller_name,r.last_sale_date,r.address,r.city,r.category,now,item.id));}else{ops.push(d.prepare(`INSERT INTO customers(id,tax_id,name,payer_name,phone,payer_contact,delivery_address,address_confirmed,photo_key,risk_class,customer_code,seller_name,last_sale_date,address,city,category,credit_limit,created_at,updated_at) VALUES(?,?,?,'','','','',0,NULL,NULL,?,?,?,?,?,?,0,?,?)`).bind(item.id,r.tax_id,r.name,r.customer_code,r.seller_name,r.last_sale_date,r.address,r.city,r.category,now,now));}}
 for(let i=0;i<ops.length;i+=50)await d.batch(ops.slice(i,i+50));await audit(authUser,'import_customers','customer',null,`Criados: ${planned.filter(x=>!x.target).length}; atualizados: ${planned.filter(x=>x.target).length}`);return Response.json({created:planned.filter(x=>!x.target).length,updated:planned.filter(x=>x.target).length});
}catch(e){const message=e instanceof Error?e.message:'';if(message.includes('UNIQUE constraint failed'))return Response.json({error:'A importação encontrou um código ou CPF/CNPJ já cadastrado com outro cliente.'},{status:400});return failure(e);}}
